name       : atom
version    : 0.204.0
release    : 2
source     :
    - https://github.com/atom/atom/archive/v0.204.0.tar.gz : cdbffc32adf6784a5a56262f1da35a0712e2ecec5d696170beefbe1ca7b36ed8
license    : MIT
summary    : Atom is a hackable text editor for the 21st century.
description: |
   Atom is a hackable text editor for the 21st century.
clang  :  no
builddeps  :
    - git
    - nodejs-devel
    - pkgconfig(gnome-keyring-1)
    - gcc
    - g++
    - sed
rundeps :
    - git
    - nodejs
build      : |
    export DESCRIPTION="Atom is a hackable text editor for the 21st century."

    mkdir -p %installroot%/usr/bin/
    script/build --build-dir %installroot%/atom-build
    script/grunt install --build-dir %installroot%/atom-build --install-dir %installroot%/usr
    rm -rf %installroot%/atom-build

    sed -e "s/<%= description %>/$DESCRIPTION/"  -e "s|<%= executable %>|/usr/bin/atom|"  -e "s|<%= iconName %>|atom|" resources/linux/atom.desktop.in > resources/linux/Atom.desktop

    install -Dm644 resources/linux/Atom.desktop %installroot%/usr/share/applications/atom.desktop
    install -Dm644 resources/atom.png %installroot%/usr/share/pixmaps/atom.png
