name       : audacious-plugins
version    : 3.6.1
release    : 1
source     :
    - http://distfiles.audacious-media-player.org/audacious-plugins-3.6.1-gtk3.tar.bz2 : 0160782fc4d5de19ada13a68e622d982c1e4f5147fcf0fd43f051a06174c99fe
license    : GPL-3.0 
summary    : Plugins for Audacious music player.
description: |
    Plugins for Audacious music player.
clang      : no
rundeps    :
    - audacious
builddeps  :
    - pkgconfig(audacious)
    - pkgconfig(libmpg123)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ogg)
    - pkgconfig(vorbis)
    - pkgconfig(flac)
    - faad-devel
    - ffmpeg-devel
    - pkgconfig(neon)
    - pkgconfig(alsa)
    - pkgconfig(libpulse)
setup      : |
    %configure  --prefix=/usr
build      : |
    %make
install    : |
    %make_install
