name        : filezilla
version     : 3.11.0
release     : 5
source     :
    - http://internode.dl.sourceforge.net/project/filezilla/FileZilla_Client/3.11.0/FileZilla_3.11.0_src.tar.bz2 : 2568a249556c87188bef47e7b8a1247d035785a005c6ad61f31e2fb212228db6
clang       : no
license     :
    - GPLv2+
summary     : The Free FTP Solution
builddeps   :
    - pkgconfig(dbus-1)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(cairo)
    - pkgconfig(atk)
    - pkgconfig(libidn)
    - pkgconfig(sqlite3)
    - pkgconfig(libidn)
    - pkgconfig(gnutls)
    - wxwidgets-devel
    - xdg-utils
description : |
    Open Source FTP Client
setup      : |
    %configure --disable-manualupdatecheck --disable-autoupdatecheck --disable-static --with-tinyxml=builtin
build      : |
    %make
install    : |
    %make_install
