name        : numix-icon-theme
version     : 0.3.391.20150530
release     : 7
source     :
    - http://ppa.launchpad.net/numix/ppa/ubuntu/pool/main/n/numix-icon-theme/numix-icon-theme_0.3+391~201505300037~ubuntu15.04.1.tar.xz : 2bd629de4384e7dc5e756609944d73acdb2d97fe4e97c9d0ba5f631b0d12d11c
license     : GPL-3.0+
summary     : The Numix Icon Theme
description : |
    Designed to look fresh, swishy and modern using white symbols on vividly
    coloured background for applications and simplistic devices, toolbars
    and status icons.
setup      : |
build      : |
install    : |
    mkdir -p %installroot%/usr/share/icons/
    mv Numix %installroot%/usr/share/icons/
    mv Numix-Light %installroot%/usr/share/icons/
