name        : numix-icon-theme
version     : 0.3.375
release     : 5
source     :
    - http://ppa.launchpad.net/numix/ppa/ubuntu/pool/main/n/numix-icon-theme/numix-icon-theme_0.3+375~201505171701~ubuntu15.04.1.tar.xz : 2131a4c91a7dc506bb5dca5d21e16d1af35fadb6aa12b16c8aeca578c8e06c57
license     : GPL-3.0+
summary     : The Numix Icon Theme
description : |
    Designed to look fresh, swishy and modern using white symbols on vividly
    coloured background for applications and simplistic devices, toolbars
    and status icons.
setup      : |
build      : |
install    : |
    mkdir -p %installroot%/usr/share/icons/
    mv Numix %installroot%/usr/share/icons/
    mv Numix-Light %installroot%/usr/share/icons/
