name       : evopop-icon-theme
version    : 0.7
release    : 6
source     :
    - https://github.com/solus-project/evopop-icon-theme/releases/download/0.7/EvoPop-0.7.tar.xz : f3dd3671baedd21c3413a0d522386565dbf5c26289c8e8130d804cd8ba6819cf
license    : CC-BY-4.0
summary    : EvoPop Icon Theme
description: |
    A simple icon theme with some google material design inspiration.
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
