name       : TLP
version    : 0.8
release    : 1
homepage   : http://linrunner.de/tlp
source     :
    - https://github.com/linrunner/TLP/archive/0.8.tar.gz : d5c0423fde7247cc519001caebd60e538ff5ef2be9456d2049303eef4da1aae3
license    : GPL-2.0
summary    : Advanced Power Management for Linux
builddeps  :
    - util-linux
    - hdparm
    - perl
    - usbutils
    - pciutils
    - systemd
    - dbus
    - bluez
description: |
    Advanced Power Management for Linux
setup      : |
    export TLP_SBIN='/usr/bin'
    export TLP_ULIB='/usr/lib/udev'
    export TLP_SYSD='/usr/lib/systemd/system'
    export TLP_NO_INIT='1'
    export TLP_NO_PMUTILS='1'
    export TLP_WITH_SYSTEMD='1'
build      : |
    %make
install    : |
    %make_install
    install -D tlp.service /usr/lib/systemd/system/